import { capitalReturnsHTML } from '../static/capital-returns.js';
import assert from 'node:assert/strict';
import {buildAnalysisPack,analysisText,analysisCSV,annualTrends,peerContext} from '../static/analysis-pack.js';
import {ANALYSIS_PROMPT} from '../static/analysis-prompt.js';
const schema={columns:[{key:'net_income',kind:'usd',label:'Net income'},{key:'pe',kind:'number',label:'P/E'},{key:'roe',kind:'percent',label:'ROE'},{key:'roic_proxy',kind:'percent',label:'ROIC proxy'},{key:'market_cap',kind:'usd',label:'Market cap'},{key:'sector',kind:'text',label:'Sector'},{key:'industry',kind:'text',label:'Industry'},{key:'financial_fetched',kind:'text',label:'Financials fetched'},{key:'income_period',kind:'text',label:'Income period'}]};
const stock={symbol:'TEST.L',name:'Target, "Company"',active:true,instrument:'stock',main_listing:true,region_code:'gb',region:'United Kingdom',sector:'Technology',industry:'Software',quote_currency:'GBp',financial_currency:'GBP',market_cap:100,pe:10,net_income:10,financial_fetched:'2026-10-01',income_period:'FY 2026-06-30',private_note:'NEVER EXPORT',financial_error:'/private SECRET',dividend_currency:'GBp',dividend_events:[{date:'2025-03-01',amount:100},{date:'2026-03-01',amount:120}],annual_income_history:{currency:'GBP',net_income:{'2024-06-30':100,'2025-06-30':140,'2026-06-30':154},revenue:{'2024-06-30':1000,'2025-06-30':1100,'2026-06-30':1200}},statement_history:{income_annual:{currency:'GBP',frequency:'annual',units:{'Diluted EPS':'currency_per_share','Diluted Average Shares':'shares'},periods:[{end_date:'2026-06-30',fetched_at:'2026-10-01',values:{'Diluted EPS':2,'Diluted Average Shares':100,'Net Income':150,'Total Revenue':1200}}]},cashflow_annual:{currency:'GBP',frequency:'annual',units:{'Operating Cash Flow':'currency','Capital Expenditure':'currency','Cash Dividends Paid':'currency'},periods:[{end_date:'2026-06-30',values:{'Operating Cash Flow':200,'Capital Expenditure':-50,'Cash Dividends Paid':-40}}]}}};
const peer=(symbol,cap,pe,ni=10,extras={})=>({...stock,symbol,name:symbol,market_cap:cap,pe,net_income:ni,...extras});
const rows=[stock,peer('P1',110,20),peer('P2',120,-5),peer('P3',130,40),peer('P4',140,null),peer('DUP',90,10,10,{name:stock.name}),peer('WRAPPER',101,1,1000,{main_listing:false}),peer('FUND',102,1,1000,{instrument:'other'}),peer('OTHER',103,1,1000,{sector:'Energy',industry:'Oil'})];
const status={snapshot:{built:'2026-10-07'},fx:{GBP:{rate:1.25,date:'2026-10-06'}}};
const pack=buildAnalysisPack(stock,rows,schema,status,{now:'2026-10-07T12:00:00Z'});
assert.equal(pack.data.derived_trends.annual.rows.at(-1).net_income,154,'newer annual cache restatement takes precedence');
assert.equal(pack.data.derived_trends.diagnosis.growth_rate_direction,'slowing');
assert.ok(Math.abs(pack.data.derived_trends.diagnosis.change_in_income_growth_pp+30)<1e-10);
assert.equal(pack.data.derived_trends.annual.rows.at(-1).fcf,150);
assert.equal(pack.data.derived_trends.annual.rows.at(-1).cash_conversion,200/154);
assert.equal(pack.data.derived_trends.annual.rows.at(-1).payout_fcf_percent,40/150*100);
assert.equal(pack.data.financial_statements.income_annual.periods[0].values_usd['Diluted EPS'],2.5);
assert.equal(pack.data.financial_statements.income_annual.periods[0].values_usd['Diluted Average Shares'],undefined);
assert.equal(pack.data.dividends.events[0].dividend_per_share,1);
assert.equal(pack.data.dividends.events[0].dividend_per_share_usd,1.25);
assert.equal(pack.data.dividends.annual.at(-1).incomplete,true);
assert.equal(pack.data.dividends.annual.at(-1).growth,null);
assert.equal(pack.data.peers.industry.count,5,'share-class duplicate and wrappers excluded');
assert.equal(pack.data.peers.industry.metrics.pe.count,3,'non-positive and missing P/E excluded');
assert.equal(pack.data.peers.industry.metrics.pe.median,20);
assert.ok(Math.abs(pack.data.peers.industry.metrics.pe.target_percentile-100/6)<1e-10);
assert.equal(pack.data.peers.selected_peers.length,4);
assert.equal(pack.data.peers.selected_peers[0].symbol,'P1');
assert.ok(!JSON.stringify(pack).includes('NEVER EXPORT'));
assert.ok(!JSON.stringify(pack).includes('SECRET'));
assert.ok(analysisText(pack).includes('<ATLAS_DATA_BUNDLE>'));
assert.ok(analysisText(pack).includes('Net Income'));
assert.equal(JSON.parse(JSON.stringify(pack)).pack_version,1);
const csv=analysisCSV(pack);
assert.ok(csv.includes('analysis_prompt'));
assert.ok(csv.includes('income_annual,TEST.L,2026-06-30,Diluted EPS,2,currency_per_share,GBP,2.5'));
assert.ok(csv.includes('income_annual,TEST.L,2026-06-30,Diluted Average Shares,100,shares,GBP,'));
assert.ok(csv.includes('payout_fcf_percent'));
assert.ok(csv.includes('target_percentile'));
assert.ok(csv.includes('fx.GBP.rate'));
assert.ok(csv.includes('"Target, ""Company"""'));
assert.ok(!csv.includes('NEVER EXPORT'));
const loss={...stock,annual_income_history:{currency:'GBP',net_income:{'2024-06-30':-10,'2025-06-30':0,'2026-06-30':10}},statement_history:{}};
assert.equal(annualTrends(loss).rows.at(-1).net_income_yoy_percent,null);
assert.equal(annualTrends(loss).rows.at(-1).net_income_yoy_absolute,10);
const quarters={statement_history:{income_quarterly:{currency:'USD',periods:['2025-06-30','2025-09-30','2025-12-31','2026-03-31','2026-06-30'].map((day,i)=>({end_date:day,values:{'Net Income':10+i*2,'Total Revenue':100}}))}}};
assert.ok(Math.abs(annualTrends(quarters,'quarterly').rows.at(-1).net_income_yoy_percent-80)<1e-10);
assert.equal(annualTrends(quarters,'quarterly').rows.at(-1).yoy_comparison_end,'2025-06-30');
const wrongCurrency={...stock,statement_history:{income_annual:{currency:'JPY',periods:[{end_date:'2026-06-30',values:{'Net Income':500000}}]}}};
assert.equal(annualTrends(wrongCurrency).rows.at(-1).net_income,154);
const missing=buildAnalysisPack({symbol:'UNKNOWN',quote_currency:'USD'},[],schema,{},{now:'2026-10-07T12:00:00Z'});
assert.equal(missing.data.peers.selected_peers.length,0);
assert.ok(missing.data.data_gaps.some(t=>t.includes('Sector')));
assert.ok(missing.data.data_gaps.some(t=>t.includes('Full statement')));
assert.equal(missing.data.capital_efficiency.roic_proxy_percent,null);
const many=Array.from({length:100},(_,i)=>peer('CAP'+i,10+i,10));
assert.equal(peerContext(many,stock,schema).selected_peers.length,24);
assert.equal(peerContext(many,stock,schema).industry.count,100);
assert.ok(ANALYSIS_PROMPT.split(/\s+/).length>2000);
for(const phrase of ['net income','share count','dividend','ROIC','ROE','positive starting','Pareto','bear, base and bull','untrusted','five-year or ten-year','cash flow','counter-case'])assert.ok(ANALYSIS_PROMPT.toLowerCase().includes(phrase.toLowerCase()),phrase);
console.log('Analysis pack: histories, restatements, losses, quarterly YoY, FX units, dividends, peer coverage, deduplication, CSV completeness, privacy and detailed prompt checks passed');

const returnsRow={...stock,roce:15,roic_proxy:10,roce_5y_avg:null,roce_5y_count:3,roce_5y_avg_reason:'Needs 5 valid years',capital_returns_history:[{end_date:'2025-06-30',roic_proxy:10,roce:15,inputs:{roce:{ebit:60,average_capital:400}},reasons:{roce:null}}]};
const returnsPack=buildAnalysisPack(returnsRow,rows,schema,status);
assert.equal(returnsPack.data.capital_efficiency.roce_percent,15);
assert.equal(returnsPack.data.capital_efficiency.roce_5y_average_percent,null);
assert.equal(returnsPack.data.capital_efficiency.roce_5y_valid_years,3);
assert.equal(returnsPack.data.capital_efficiency.annual_history[0].inputs.roce.ebit,60);
assert.ok(analysisCSV(returnsPack).includes('capital_efficiency.annual_history.0.inputs.roce.ebit,60'));
assert.ok(returnsPack.data.data_gaps.some(v=>v.includes('ROCE 5Y average unavailable: Needs 5 valid years')));
const returnsHTML=capitalReturnsHTML(returnsRow);
assert.ok(returnsHTML.includes('3/5 valid annual ratios')&&returnsHTML.includes('15.00%')&&returnsHTML.includes('2025-06-30'));
assert.ok(capitalReturnsHTML({...returnsRow,roce_reason:'<script>unsafe</script>',roce:null}).includes('&lt;script&gt;'));
assert.ok(ANALYSIS_PROMPT.includes('not CAGR'));
