import assert from 'node:assert/strict';
import { quantile, axisScale, quadrantModel, regression } from '../static/quadrant-math.js';
const fields = { x: { kind:'usd' }, y:{kind:'integer'} };
const settings = { x:'x', y:'y', xPrefer:'higher', yPrefer:'higher', xScale:'linear', yScale:'linear', split:'median' };
const rows = [-4,-2,2,4].map((x,i)=>({symbol:String(i),x,y:[1,3,1,3][i]}));
assert.equal(quantile([1,2,3,1000],.5),2.5);
assert.equal(quantile([], .5),null);
const model = quadrantModel([...rows,{x:null,y:4},{x:NaN,y:3},{x:1,y:Infinity}],settings,fields);
assert.equal(model.points.length,4); assert.equal(model.missing,3);
assert.deepEqual(model.counts,{dream:1,x:1,y:1,lagging:1});
assert.equal(model.xcut,0); assert.equal(model.ycut,2);
const ties = quadrantModel([{x:0,y:0},{x:0,y:0},{x:1,y:1}],settings,fields);
assert.equal(ties.counts.dream,3); assert.equal(ties.fit.r2,1);
const zero = quadrantModel([{x:0,y:0}],settings,fields);
assert.equal(zero.points.length,1); assert.equal(zero.fit,null); assert.ok(zero.xdomain[0]<0 && zero.xdomain[1]>0);
const low = quadrantModel(rows,{...settings,xPrefer:'lower',split:'quartile'},fields);
assert.equal(low.xcut,-2.5); assert.equal(low.ycut,3); assert.equal(low.points.find(p=>p.row.symbol==='0').zone,'x');
const custom = quadrantModel(rows,{...settings,split:'custom',xCut:-10,yCut:10},fields);
assert.equal(custom.counts.x,4); assert.ok(custom.xdomain[0]<-10);
assert.throws(()=>quadrantModel(rows,{...settings,split:'custom',xCut:null,yCut:1},fields));
const log = axisScale([-1e9,0,1e9],'symlog','higher','usd');
assert.equal(log.forward(0),0); assert.ok(log.forward(-1e9)<0);
assert.ok(Math.abs(log.inverse(log.forward(-1e9))+1e9)<.001);
const rank = axisScale([0,0,0,1,2],'rank');
assert.equal(rank.forward(0),25); assert.equal(rank.forward(2),100);
assert.equal(rank.inverse(100),2);
const lower = axisScale([1,2,3],'rank','lower'); assert.equal(lower.forward(3),-100); assert.equal(lower.percentile(1),100);
const fit = regression([1,2,3,4].map(tx=>({tx,ty:2*tx+7})));
assert.equal(fit.slope,2); assert.equal(fit.intercept,7); assert.equal(fit.r2,1);
assert.equal(regression([{tx:1,ty:1},{tx:1,ty:2},{tx:1,ty:3}]),null);
assert.equal(regression([{tx:1,ty:1},{tx:2,ty:1},{tx:3,ty:1}]),null);
assert.equal(regression([{tx:1,ty:2},{tx:2,ty:3}]),null);
const all = quadrantModel(Array.from({length:1000},(_,x)=>({x,y:x})),settings,fields);
assert.equal(all.points.length,1000); assert.equal(all.xcut,499.5); assert.equal(all.counts.dream,500);
console.log('Quadrant quantiles, full-population counts, ties, losses, scales and regression checks passed');
